apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: hello-world
  name: hello
spec:
  hard:
    requests:
      cpu: "2000m"
      memory: "2Gi"
    limits:
      cpu: "4000m"
      memory: "4Gi"